name: training
on: [push]
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Linux"
      - run: pwd
      - name: Checking github with reserve variable
        run: ls ${{github.workspace}}