name: Git repo to S3
on: 
    push:
        branches: [main]
jobs:
  JobClone:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Current repo
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Creating SG
        run: |
              aws ec2 create-security-group \
                --group-name sgganeshgithubactions \
                --description "test desc" \
                --vpc-id vpc-08e5bc89ab4518ee3